<a href="https://colab.research.google.com/github/ayushranjan6456/HydrogenPrediction/blob/main/Hydrogen_Prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [101]:
df = pd.read_csv('/content/gdrive/My Drive/dataset/interpolated_merged.csv')

#Drop the unnamed column with index of all 7 cycles individually
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

df

time        pH       VFA        COD        Gas
0      0.000000  6.000000  3.310000  11.200000   0.000000
1      0.241206  5.998204  3.310584  11.227403   0.179567
2      0.482412  5.996256  3.311476  11.251849   0.366206
3      0.723618  5.994160  3.312668  11.273404   0.559677
4      0.964824  5.991923  3.314152  11.292135   0.759741
...         ...       ...       ...        ...        ...
1395  47.035176  4.947926  4.731427   6.214625  44.151661
1396  47.276382  4.936978  4.742158   6.144786  44.818456
1397  47.517588  4.925355  4.753809   6.072439  45.514966
1398  47.758794  4.913037  4.766412   5.997529  46.241908
1399  48.000000  4.900000  4.780000   5.920000  47.000000

[1400 rows x 5 columns]

In [102]:
from sklearn.model_selection import train_test_split

# input
x = df.iloc[:, [0,1,2,3]].values

# output
y = df.iloc[:, 4].values


In [103]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()

# Now, it is very important to perform feature scaling here because pH, time, COD, VFA values lie in different ranges. 
# If we don’t scale the features then the some features will dominate the other when the model finds the nearest neighbor to a data point in the data space. 
x = sc_x.fit_transform(x)

#Here all features values are scaled and now there in the -1 to 1.

np.set_printoptions(suppress = True)   #to not print in scientific notation
print (x[0:10, :])


[[-1.7234121   1.2581477  -1.52120333  1.45837565]
 [-1.70609137  1.2529742  -1.5200075   1.47681541]
 [-1.68877065  1.24736082 -1.51818071  1.49326538]
 [-1.67144992  1.24132368 -1.51573909  1.5077703 ]
 [-1.6541292   1.2348789  -1.5126988   1.52037492]
 [-1.63680847  1.2280426  -1.50907596  1.53112397]
 [-1.61948775  1.22083089 -1.50488672  1.54006221]
 [-1.60216702  1.2132599  -1.50014724  1.54723437]
 [-1.5848463   1.20534573 -1.49487363  1.5526852 ]
 [-1.56752558  1.19710451 -1.48908206  1.55645944]]


In [104]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(x, y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)


#X_train 4 input features, 70% of full dataset)
# X_val (4 input features, 15% of full dataset)
# X_test (4 input features, 15% of full dataset)

#Building the Neural Network

In [119]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(32, activation='relu', input_dim=4),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid'),
])

#Filling in the best numbers. sgd - stochastic gradient descent

model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

hist = model.fit(X_train, Y_train,
          batch_size=15, epochs=150,
          validation_data=(X_val, Y_val))

Epoch 1/150
66/66 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 2/150
66/66 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 3/150
66/66 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 4/150
66/66 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 5/150
66/66 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 6/150
66/66 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 7/150
66/66 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.0041 - val_loss: nan - val_accuracy: 0.0048
Epoch 8/150
66/66 [==============================] - 0s

In [123]:

print('Accuracy : {}'.format(100*model.evaluate(X_test, Y_test)[1]))


7/7 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0095
Accuracy : 0.9523809887468815
